### ISSUE TITLE
Warning docker utils

### ISSUE THREAD

**Issue by jvican** [coursera/courseraprogramming#30]
Running the latest version of `courseraprogramming`, I always get this if I run `grade local`:

```
WARNING:py.warnings:/localhome/dockermoocs/.local/lib/python2.7/site-packages/docker/utils/utils.py:485: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
```

**Comment by saeta** [comment]
Thanks for reporting @jvican . We'll look into upgrading our `docker-py` version to get rid of that error.

**Comment by nrhodes** [comment]
Commit #69 should fix this issue.

**Comment by saeta** [comment]
This should be fixed now. Thanks!
