### ISSUE TITLE
Instructions on how to authenticate

### ISSUE THREAD

**Issue by asmod3us** [coursera/courseraprogramming#42]
I was missing instructions on how to authenticate the cli. I figured out that there's a configure check-auth command, but it's not documented here.

After visiting the url it generates to authorize the app, I encountered a redirect to a localhost:9876 port. As I'm running the cli in a vm (based on discussion in #38, #39) this required further network setup. I added `config.vm.network "forwarded_port", guest: 9876, host: 9876` in my vagrant box config, and after `vagrant halt; vagrant up` I was able to complete authorization.

Maybe it's worth adding some instructions in the readme on this?

**Comment by saeta** [comment]
Hey @asmod3us thanks for reaching out. That's a great way to do it. It'd be great to document that way, but I'm curious to hear what you think of the following solution:
1. install `courseraprogramming` locally.
2. run `courseraprogramming configure check-auth` to set up the authorization information.
3. Copy the file `~/.coursera/oauth2_cache.pickle` to the VM.
4. (Optional) Run `courseraprogramming configure display-auth-cache` to verify success.

**Comment by asmod3us** [comment]
I guess that's much better, thanks!
