### ISSUE TITLE
possible bug in api

### ISSUE THREAD

**Issue by liufengyun** [coursera/courseraprogramming#58]
When I call the api `https://api.coursera.org/api/gridExecutorCreationAttempts.v1` with `reservedCpu: 2`, I got following error message:

```
  "message": "reservedCpu 1 is not valid, must be one of Set(1024, 2048)",
```

It seems the server mistakes cpu with memory.

**Comment by saeta** [comment]
Hey @liufengyun. Actually, the server is doing the right thing. The code [here](https://github.com/coursera/courseraprogramming/blob/master/courseraprogramming/commands/upload.py#L243) does the scaling by 1024. (It is set up this way to eventually allow partial CPU allotment in the future, but for now, it is disabled. 1024=1CPU, 2048=2CPUs.

**Comment by liufengyun** [comment]
Thanks a lot for explanation!

**Comment by saeta** [comment]
No problem! Thanks for being patient & working with us on using our systems!
