### ISSUE TITLE
tar.gz on upload?

### ISSUE THREAD

**Issue by ccoffrin** [coursera/courseraprogramming#61]
When using the upload feature, is it possible to save the image as a tar.gz?  It makes about a 2x difference in image size in my experience.

**Comment by saeta** [comment]
That's a great idea. Not sure when we'll be able to get to it but we'll keep this ticket open until we can get this resolved.

**Comment by nrhodes** [comment]
I have several courses which support many programming languages that a student can use.  We're finding it extremely difficult to keep the image size under 2Gb. Over that size, the image can't be uploaded.  Any chance we can bump the priority on supporting compressed images?

**Comment by sashi-coursera** [comment]
Now we support up to image size up to 8GB.
