### ISSUE TITLE
Upload and Publish

### ISSUE THREAD

**Issue by ccoffrin** [coursera/courseraprogramming#63]
I attempted to write a bash script that would upload a new grader and then publish it.  I ran into an issue where publish command returned,

`WARNING:root:We are still processing your grader for your assignment with item id FktbJ.  Please try again soon.`

Is there a way I can make either the upload or publish commands block until processing is complete?

**Comment by saeta** [comment]
As of now, that's not yet possible. Most others who use this just sleep for a couple minutes between upload and publish. (The smaller the image, the faster the time spent pending. It can be as short as ten seconds, and as long as many minutes.)

The server APIs actually do expose the status of the processing step, but we haven't yet built in the polling into this CLI.

**Comment by sashi-coursera** [comment]
Good idea, we probably won't get to it. We are considering other ways to improve this.
