### ISSUE TITLE
Can't request more than 2048MB memory with --grader-memory-limit

### ISSUE THREAD

**Issue by kevin-wayne** [coursera/courseraprogramming#71]
The documentation says --grader-memory-limit takes a values of 1024, 2048, 3072, or 4096 but it rejects the values 3072 and 4096.

Same problem exists with --grader-CPU values of 3 or 4.

Either update the documentation or the code.

**Comment by sashi-coursera** [comment]
Hi @kevin-wayne - unfortunately, these issues were not monitored/maintained. I am going to take a look at each one of these now. Today, I merged the change which now allows all these options. To use the updated courseraprogramming tool - please use these steps described at : https://github.com/coursera/programming-assignments-demo/tree/master/custom-graders#march-2018-alert
